function dateFormater(timestamp) {
  const date = new Date(timestamp)
  var year = date.getFullYear();
  var month = date.getMonth();
  var day = date.getDay();
  return `${day < 10 ? '0' + day : day}/${month < 10 ? '0' + month : month}/${year}`;
}
function initials(user) {
  const splitedName = user.displayName.split(" ");
  if (splitedName.length <= 1) return user.displayName[0].toUpperCase(); ``
  const firstNameInitial = splitedName[0].split("")[0];
  const lastNameInitial = splitedName[1].split("")[0];
  return firstNameInitial.toUpperCase() + lastNameInitial.toUpperCase();
}
function currencyForamter(amount, currency) {
  return Intl.NumberFormat("fr-CH", { style: "currency", currency: currency }).format(amount)
}

function generateTemplate(userName){
  let template = {
    description: "this is a template generated by us to give an example",
    name: "Sareta template",
    expenses: [
      {
        name: "Emergency roadside",
        amount: 0,
        isActive: true,
        frequency: "Yearly",
        assignee: "",
      },
      {
        name: "Car licence plate",
        amount: 0,
        isActive: true,
        frequency: "Yearly",
        assignee: "",
      },
      { name: "Driver's license", amount: 0, isActive: true, frequency: "Yearly", assignee: "" },
      { name: "Accountant", amount: 0, isActive: true, frequency: "Yearly", assignee: "" },
      { name: "Home insurance", amount: 0, isActive: true, frequency: "Monthly", assignee: "" },
      { name: "Car gas", amount: 0, isActive: true, frequency: "Monthly", assignee: "" },
      { name: "Food", amount: 0, isActive: true, frequency: "Monthly", assignee: "" },
      { name: "Car insurance", amount: 0, isActive: true, frequency: "Monthly", assignee: "" },
      {
        name: "Water and electrecity",
        amount: 0,
        isActive: true,
        frequency: "Monthly",
      },
      { name: "Rent/Mortgage", amount: 0, isActive: true, frequency: "Monthly" },
      {
        name: "Household utilities",
        amount: 0,
        isActive: true,
        frequency: "Monthly",
      },
      { name: "Cellphone plans", amount: 0, isActive: true, frequency: "Monthly", assignee: "" },
      {
        name: "Other monthly subscriptions",
        amount: 0,
        isActive: true,
        frequency: "Monthly",
      },
      {
        name: "Outside activites",
        amount: 0,
        isActive: true,
        frequency: "Monthly",
      },
      { name: "Relief capital", amount: 0, isActive: true, frequency: "Yearly", assignee: "" },
      { name: "Car maintenance", amount: 0, isActive: true, frequency: "Yearly", assignee: "" },
      { name: "Home maintenance", amount: 0, isActive: true, frequency: "Yearly", assignee: "" },
    ],
  };
  template.expenses.forEach((el) => (el.assignee = userName));
  return template
}

export {
  currencyForamter,
  dateFormater,
  initials,
  generateTemplate
};
